/**
 * ARCHIVO GENERADO por scripts/generar-ubigeo.mjs - no editar a mano.
 *
 * Provincias y distritos del Peru que apuntan a un unico departamento, sacados
 * del padron de ubigeo del front (viatika/src/app/constants/peru-locations.ts).
 * Los nombres que se repiten entre departamentos quedan fuera: mandarlos al
 * departamento equivocado esconde el gasto en otra region.
 *
 * Origen: 196 provincias y 1869 distritos.
 * 1652 nombres sin ambiguedad, 97 descartados por repetirse.
 */
export const UBIGEO_A_DEPARTAMENTO: Record<string, string> = {
  "abancay": "Apurímac",
  "abelardo pardo lezameta": "Áncash",
  "acari": "Arequipa",
  "acas": "Áncash",
  "accha": "Cusco",
  "accomarca": "Ayacucho",
  "achaya": "Puno",
  "achoma": "Arequipa",
  "acobambilla": "Huancavelica",
  "acochaca": "Áncash",
  "acocro": "Ayacucho",
  "acolla": "Junín",
  "acomayo": "Cusco",
  "acopampa": "Áncash",
  "acopia": "Cusco",
  "acora": "Puno",
  "acoria": "Huancavelica",
  "acos": "Cusco",
  "acos vinchos": "Ayacucho",
  "acostambo": "Huancavelica",
  "acraquia": "Huancavelica",
  "aczo": "Áncash",
  "agallpampa": "La Libertad",
  "agua blanca": "San Martín",
  "aguas verdes": "Tumbes",
  "ahuac": "Junín",
  "ahuaycha": "Huancavelica",
  "aija": "Áncash",
  "ajoyani": "Puno",
  "alberto leveau": "San Martín",
  "alca": "Arequipa",
  "alcamenca": "Ayacucho",
  "alexander von humboldt": "Ucayali",
  "alfonso ugarte": "Áncash",
  "alis": "Lima",
  "alonso de alvarado": "San Martín",
  "alto amazonas": "Loreto",
  "alto biavo": "San Martín",
  "alto de la alianza": "Tacna",
  "alto inambari": "Puno",
  "alto laran": "Ica",
  "alto nanay": "Loreto",
  "alto pichigua": "Cusco",
  "alto saposoa": "San Martín",
  "alto selva alegre": "Arequipa",
  "alto tapiche": "Loreto",
  "amantani": "Puno",
  "amarilis": "Huánuco",
  "amashca": "Áncash",
  "ambar": "Lima",
  "ambo": "Huánuco",
  "amotape": "Piura",
  "ananea": "Puno",
  "anapia": "Puno",
  "ancahuasi": "Cusco",
  "anchihuay": "Ayacucho",
  "anchonga": "Huancavelica",
  "anco huallo": "Apurímac",
  "ancon": "Lima",
  "andagua": "Arequipa",
  "andahuaylas": "Apurímac",
  "andahuaylillas": "Cusco",
  "andajes": "Lima",
  "andamarca": "Junín",
  "andarapa": "Apurímac",
  "andaray": "Arequipa",
  "andaymarca": "Huancavelica",
  "andoas": "Loreto",
  "andres avelino caceres dorregaray": "Ayacucho",
  "angaraes": "Huancavelica",
  "angasmarca": "La Libertad",
  "anguia": "Cajamarca",
  "anra": "Áncash",
  "antabamba": "Apurímac",
  "antauta": "Puno",
  "antioquia": "Lima",
  "antonio raymondi": "Áncash",
  "aparicio pomares": "Huánuco",
  "apata": "Junín",
  "aplao": "Arequipa",
  "apongo": "Ayacucho",
  "aquia": "Áncash",
  "arahuay": "Lima",
  "aramango": "Amazonas",
  "arancay": "Huánuco",
  "arapa": "Puno",
  "arenal": "Piura",
  "arma": "Huancavelica",
  "ascension": "Huancavelica",
  "ascope": "La Libertad",
  "asia": "Lima",
  "asillo": "Puno",
  "asquipata": "Ayacucho",
  "atalaya": "Ucayali",
  "ataquero": "Áncash",
  "ataura": "Junín",
  "atavillos alto": "Lima",
  "atavillos bajo": "Lima",
  "ate": "Lima",
  "atico": "Arequipa",
  "atiquipa": "Arequipa",
  "atuncolla": "Puno",
  "aucallama": "Lima",
  "aucara": "Ayacucho",
  "aurahua": "Huancavelica",
  "awajun": "San Martín",
  "ayabaca": "Piura",
  "ayahuanco": "Ayacucho",
  "ayapata": "Puno",
  "ayauca": "Lima",
  "ayavi": "Huancavelica",
  "aymaraes": "Apurímac",
  "ayna": "Ayacucho",
  "ayo": "Arequipa",
  "bagua": "Amazonas",
  "bagua grande": "Amazonas",
  "bajo biavo": "San Martín",
  "balsapuerto": "Loreto",
  "balsas": "Amazonas",
  "bambas": "Áncash",
  "banos": "Huánuco",
  "barranco": "Lima",
  "barranquita": "San Martín",
  "bella union": "Arequipa",
  "bellavista de la union": "Piura",
  "bernal": "Piura",
  "bolognesi": "Áncash",
  "bongara": "Amazonas",
  "brena": "Lima",
  "buena vista alta": "Áncash",
  "buldibuyo": "La Libertad",
  "cabanaconde": "Arequipa",
  "cabanilla": "Puno",
  "cabanillas": "Puno",
  "cacatachi": "San Martín",
  "caceres del peru": "Áncash",
  "cachachi": "Cajamarca",
  "cachicadan": "La Libertad",
  "cachimayo": "Cusco",
  "cacra": "Lima",
  "cahuac": "Huánuco",
  "cahuacho": "Arequipa",
  "cahuapanas": "Loreto",
  "caicay": "Cusco",
  "cairani": "Tacna",
  "caja": "Huancavelica",
  "cajabamba": "Cajamarca",
  "cajacay": "Áncash",
  "cajamarquilla": "Áncash",
  "cajaruro": "Amazonas",
  "cajatambo": "Lima",
  "cajay": "Áncash",
  "calamarca": "La Libertad",
  "calana": "Tacna",
  "calango": "Lima",
  "calapuja": "Puno",
  "calca": "Cusco",
  "caleta de carquin": "Lima",
  "callahuanca": "Lima",
  "callalli": "Arequipa",
  "callanmarca": "Huancavelica",
  "callayuc": "Cajamarca",
  "calleria": "Ucayali",
  "calquis": "Cajamarca",
  "calzada": "San Martín",
  "camana": "Arequipa",
  "camanti": "Cusco",
  "camilaca": "Tacna",
  "caminaca": "Puno",
  "campanilla": "San Martín",
  "camporredondo": "Amazonas",
  "campoverde": "Ucayali",
  "canaria": "Ayacucho",
  "canaris": "Lambayeque",
  "canas": "Cusco",
  "canayre": "Ayacucho",
  "canchabamba": "Huánuco",
  "canchaque": "Piura",
  "canchayllo": "Junín",
  "canchis": "Cusco",
  "candarave": "Tacna",
  "canete": "Lima",
  "cangallo": "Ayacucho",
  "canis": "Áncash",
  "canoas de punta sal": "Tumbes",
  "canta": "Lima",
  "capachica": "Puno",
  "capacmarca": "Cusco",
  "capaya": "Apurímac",
  "capazo": "Puno",
  "capelo": "Loreto",
  "capillas": "Huancavelica",
  "carabamba": "La Libertad",
  "carabaya": "Puno",
  "carabayllo": "Lima",
  "caracoto": "Puno",
  "carampoma": "Lima",
  "carania": "Lima",
  "carapo": "Ayacucho",
  "caraveli": "Arequipa",
  "caraybamba": "Apurímac",
  "caraz": "Áncash",
  "carhuacallanga": "Junín",
  "carhuamayo": "Junín",
  "carhuanca": "Ayacucho",
  "carhuapampa": "Áncash",
  "carhuaz": "Áncash",
  "carlos fermin fitzcarrald": "Áncash",
  "carmen alto": "Ayacucho",
  "carmen de la legua reynoso": "Callao",
  "carmen salcedo": "Ayacucho",
  "carumas": "Moquegua",
  "casa grande": "La Libertad",
  "casca": "Áncash",
  "cascapara": "Áncash",
  "cascas": "La Libertad",
  "cashapampa": "Áncash",
  "casitas": "Tumbes",
  "casma": "Áncash",
  "caspisapa": "San Martín",
  "castillo grande": "Huánuco",
  "castrovirreyna": "Huancavelica",
  "catac": "Áncash",
  "catacaos": "Piura",
  "catache": "Cajamarca",
  "catahuasi": "Lima",
  "catilluc": "Cajamarca",
  "caujul": "Lima",
  "cayalti": "Lambayeque",
  "cayara": "Ayacucho",
  "cayarani": "Arequipa",
  "caylloma": "Arequipa",
  "cayma": "Arequipa",
  "cayna": "Huánuco",
  "caynarachi": "San Martín",
  "ccapi": "Cusco",
  "ccarhuayo": "Cusco",
  "ccatca": "Cusco",
  "ccochaccasa": "Huancavelica",
  "ccorca": "Cusco",
  "celendin": "Cajamarca",
  "cerro azul": "Lima",
  "cerro colorado": "Arequipa",
  "chaca": "Ayacucho",
  "chacabamba": "Huánuco",
  "chacapalpa": "Junín",
  "chacapampa": "Junín",
  "chacas": "Áncash",
  "chacayan": "Pasco",
  "chaccho": "Áncash",
  "chachapoyas": "Amazonas",
  "chachas": "Arequipa",
  "chaclacayo": "Lima",
  "chacoche": "Apurímac",
  "chadin": "Cajamarca",
  "chaglla": "Huánuco",
  "chala": "Arequipa",
  "chalaco": "Piura",
  "chalamarca": "Cajamarca",
  "chalcos": "Ayacucho",
  "chalhuanca": "Apurímac",
  "challabamba": "Cusco",
  "challhuahuacho": "Apurímac",
  "chamaca": "Cusco",
  "chambara": "Junín",
  "chancaybanos": "Cajamarca",
  "chanchamayo": "Junín",
  "changuillo": "Ica",
  "chao": "La Libertad",
  "chaparra": "Arequipa",
  "chapimarca": "Apurímac",
  "characato": "Arequipa",
  "charat": "La Libertad",
  "charcana": "Arequipa",
  "chaupimarca": "Pasco",
  "chavin": "Ica",
  "chavin de huantar": "Áncash",
  "chavin de pariarca": "Huánuco",
  "chavina": "Ayacucho",
  "chavinillo": "Huánuco",
  "chazuta": "San Martín",
  "checacupe": "Cusco",
  "checca": "Cusco",
  "checras": "Lima",
  "chepen": "La Libertad",
  "chetilla": "Cajamarca",
  "cheto": "Amazonas",
  "chicama": "La Libertad",
  "chicche": "Junín",
  "chichas": "Arequipa",
  "chicla": "Lima",
  "chiclayo": "Lambayeque",
  "chiguata": "Arequipa",
  "chiguirip": "Cajamarca",
  "chilcas": "Ayacucho",
  "chilcaymarca": "Arequipa",
  "chilcayoc": "Ayacucho",
  "chilete": "Cajamarca",
  "chiliquin": "Amazonas",
  "chillia": "La Libertad",
  "chimban": "Cajamarca",
  "chimbote": "Áncash",
  "chincha": "Ica",
  "chincha alta": "Ica",
  "chincha baja": "Ica",
  "chinchao": "Huánuco",
  "chinchaypujio": "Cusco",
  "chinchero": "Cusco",
  "chincheros": "Apurímac",
  "chinchihuasi": "Huancavelica",
  "chincho": "Huancavelica",
  "chingalpo": "Áncash",
  "chingas": "Áncash",
  "chipao": "Ayacucho",
  "chipurana": "San Martín",
  "chiquian": "Áncash",
  "chirimoto": "Amazonas",
  "chirinos": "Cajamarca",
  "chisquilla": "Amazonas",
  "chivay": "Arequipa",
  "chochope": "Lambayeque",
  "choco": "Arequipa",
  "chocope": "La Libertad",
  "chocos": "Lima",
  "chojata": "Moquegua",
  "cholon": "Huánuco",
  "chongos alto": "Junín",
  "chongos bajo": "Junín",
  "chongoyape": "Lambayeque",
  "chontabamba": "Pasco",
  "chontali": "Cajamarca",
  "choras": "Huánuco",
  "choropampa": "Cajamarca",
  "choros": "Cajamarca",
  "chorrillos": "Lima",
  "chota": "Cajamarca",
  "chucuito": "Puno",
  "chugay": "La Libertad",
  "chugur": "Cajamarca",
  "chulucanas": "Piura",
  "chumbivilcas": "Cusco",
  "chumpi": "Ayacucho",
  "chumuch": "Cajamarca",
  "chungui": "Ayacucho",
  "chupa": "Puno",
  "chupaca": "Junín",
  "chupamarca": "Huancavelica",
  "chupuro": "Junín",
  "chuquibambilla": "Apurímac",
  "chuquis": "Huánuco",
  "churcampa": "Huancavelica",
  "churubamba": "Huánuco",
  "churuja": "Amazonas",
  "chuschi": "Ayacucho",
  "cieneguilla": "Lima",
  "circa": "Apurímac",
  "ciudad nueva": "Tacna",
  "coalaque": "Moquegua",
  "coasa": "Puno",
  "coata": "Puno",
  "coayllo": "Lima",
  "cocabamba": "Amazonas",
  "cocachacra": "Arequipa",
  "cocas": "Huancavelica",
  "cochamal": "Amazonas",
  "cochamarca": "Lima",
  "cochapeti": "Áncash",
  "cocharcas": "Apurímac",
  "cochorco": "La Libertad",
  "codo del pozuzo": "Huánuco",
  "coishco": "Áncash",
  "cojata": "Puno",
  "colan": "Piura",
  "colasay": "Cajamarca",
  "colcamar": "Amazonas",
  "colcha": "Cusco",
  "colonia": "Lima",
  "colpas": "Huánuco",
  "colquemarca": "Cusco",
  "colquepata": "Cusco",
  "colquioc": "Áncash",
  "colta": "Ayacucho",
  "comandante noel": "Áncash",
  "combapata": "Cusco",
  "conayca": "Huancavelica",
  "conchamarca": "Huánuco",
  "conchan": "Cajamarca",
  "conchucos": "Áncash",
  "condebamba": "Cajamarca",
  "condesuyos": "Arequipa",
  "condorcanqui": "Amazonas",
  "condormarca": "La Libertad",
  "condoroma": "Cusco",
  "conduriri": "Puno",
  "congalla": "Huancavelica",
  "congas": "Áncash",
  "conila": "Amazonas",
  "conima": "Puno",
  "constitucion": "Pasco",
  "contamana": "Loreto",
  "contralmirante villar": "Tumbes",
  "contumaza": "Cajamarca",
  "copa": "Lima",
  "copallin": "Amazonas",
  "copani": "Puno",
  "coracora": "Ayacucho",
  "corani": "Puno",
  "corculla": "Ayacucho",
  "cordova": "Huancavelica",
  "coris": "Áncash",
  "coronel castaneda": "Ayacucho",
  "coronel gregorio albarracin lanchipa": "Tacna",
  "coronel portillo": "Ucayali",
  "corongo": "Áncash",
  "corosha": "Amazonas",
  "corrales": "Tumbes",
  "cortegana": "Cajamarca",
  "cosme": "Huancavelica",
  "cosspan": "Cajamarca",
  "cotabambas": "Apurímac",
  "cotahuasi": "Arequipa",
  "cotaparaco": "Áncash",
  "cotaruse": "Apurímac",
  "coviriali": "Junín",
  "coya": "Cusco",
  "coyllurqui": "Apurímac",
  "cristo nos valga": "Piura",
  "crucero": "Puno",
  "cuchumbaya": "Moquegua",
  "cuispes": "Amazonas",
  "cujillo": "Cajamarca",
  "culebras": "Áncash",
  "cullhuas": "Junín",
  "cumba": "Amazonas",
  "cunumbuqui": "San Martín",
  "cupi": "Puno",
  "cupisnique": "Cajamarca",
  "cura mori": "Piura",
  "curahuasi": "Apurímac",
  "curasco": "Apurímac",
  "curgos": "La Libertad",
  "curibaya": "Tacna",
  "curicaca": "Junín",
  "curimana": "Ucayali",
  "curpahuasi": "Apurímac",
  "cusca": "Áncash",
  "cusipata": "Cusco",
  "cutervo": "Cajamarca",
  "cuturapi": "Puno",
  "cuyocuyo": "Puno",
  "daniel alcides carrion": "Pasco",
  "daniel alomia robles": "Huánuco",
  "daniel hernandez": "Huancavelica",
  "datem del maranon": "Loreto",
  "dean valdivia": "Arequipa",
  "desaguadero": "Puno",
  "dos de mayo": "Huánuco",
  "echarati": "Cusco",
  "eduardo villanueva": "Cajamarca",
  "el agustino": "Lima",
  "el algarrobal": "Moquegua",
  "el alto": "Piura",
  "el carmen de la frontera": "Piura",
  "el cenepa": "Amazonas",
  "el collao": "Puno",
  "el dorado": "San Martín",
  "el eslabon": "San Martín",
  "el ingenio": "Ica",
  "el mantaro": "Junín",
  "el milagro": "Amazonas",
  "el oro": "Apurímac",
  "el parco": "Amazonas",
  "el prado": "Cajamarca",
  "el tallan": "Piura",
  "el tambo": "Junín",
  "eleazar guzman barron": "Áncash",
  "elias soplin vargas": "San Martín",
  "emilio san martin": "Loreto",
  "encanada": "Cajamarca",
  "espinar": "Cusco",
  "estique": "Tacna",
  "estique pampa": "Tacna",
  "eten": "Lambayeque",
  "eten puerto": "Lambayeque",
  "fernando lores": "Loreto",
  "ferrenafe": "Lambayeque",
  "fidel olivas escudero": "Áncash",
  "fitzcarrald": "Madre de Dios",
  "florencia de mora": "La Libertad",
  "florida": "Amazonas",
  "frias": "Piura",
  "gamarra": "Apurímac",
  "general sanchez cerro": "Moquegua",
  "gorgor": "Lima",
  "goyllarisquizga": "Pasco",
  "gran chimu": "La Libertad",
  "granada": "Amazonas",
  "grau": "Apurímac",
  "gregorio pita": "Cajamarca",
  "grocio prado": "Ica",
  "guadalupe": "La Libertad",
  "guadalupito": "La Libertad",
  "guzmango": "Cajamarca",
  "habana": "San Martín",
  "haquira": "Apurímac",
  "hermilio valdizan": "Huánuco",
  "heroes albarracin": "Tacna",
  "heroinas toledo": "Junín",
  "hongos": "Lima",
  "honoria": "Huánuco",
  "huabal": "Cajamarca",
  "huac huas": "Ayacucho",
  "huacachi": "Áncash",
  "huacana": "Ayacucho",
  "huacar": "Huánuco",
  "huacaschuque": "Áncash",
  "huacaybamba": "Huánuco",
  "huaccana": "Apurímac",
  "huacchis": "Áncash",
  "huachac": "Junín",
  "huachis": "Áncash",
  "huacho": "Lima",
  "huachocolpa": "Huancavelica",
  "huachon": "Pasco",
  "huachos": "Huancavelica",
  "huachupampa": "Lima",
  "huacllan": "Áncash",
  "huacrachuco": "Huánuco",
  "huacrapuquio": "Junín",
  "huacullani": "Puno",
  "hualgayoc": "Cajamarca",
  "hualhuas": "Junín",
  "huallaga": "San Martín",
  "huallanca": "Áncash",
  "hualmay": "Lima",
  "huamachuco": "La Libertad",
  "huamali": "Junín",
  "huamalies": "Huánuco",
  "huamancaca chico": "Junín",
  "huamanga": "Ayacucho",
  "huamanguilla": "Ayacucho",
  "huamanquiquia": "Ayacucho",
  "huamantanga": "Lima",
  "huamatambo": "Huancavelica",
  "huambalpa": "Ayacucho",
  "huambos": "Cajamarca",
  "huampara": "Lima",
  "huanca": "Arequipa",
  "huanca huanca": "Huancavelica",
  "huanca sancos": "Ayacucho",
  "huancan": "Junín",
  "huancane": "Puno",
  "huancano": "Ica",
  "huancapi": "Ayacucho",
  "huancapon": "Lima",
  "huancarama": "Apurímac",
  "huancarani": "Cusco",
  "huancaray": "Apurímac",
  "huancaraylla": "Ayacucho",
  "huancarqui": "Arequipa",
  "huancas": "Amazonas",
  "huancaspata": "La Libertad",
  "huancaya": "Lima",
  "huancayo": "Junín",
  "huanchaco": "La Libertad",
  "huanchay": "Áncash",
  "huando": "Huancavelica",
  "huandoval": "Áncash",
  "huanec": "Lima",
  "huangascar": "Lima",
  "huanipaca": "Apurímac",
  "huanoquite": "Cusco",
  "huanta": "Ayacucho",
  "huantar": "Áncash",
  "huanuara": "Tacna",
  "huanuhuanu": "Arequipa",
  "huanza": "Lima",
  "huaquirca": "Apurímac",
  "huaral": "Lima",
  "huaranchal": "La Libertad",
  "huarango": "Cajamarca",
  "huaraz": "Áncash",
  "huari": "Áncash",
  "huariaca": "Pasco",
  "huaribamba": "Huancavelica",
  "huaricolca": "Junín",
  "huaripampa": "Junín",
  "huarmaca": "Piura",
  "huarmey": "Áncash",
  "huaro": "Cusco",
  "huarochiri": "Lima",
  "huarocondo": "Cusco",
  "huaros": "Lima",
  "huasahuasi": "Junín",
  "huasicancha": "Junín",
  "huasmin": "Cajamarca",
  "huaso": "La Libertad",
  "huasta": "Áncash",
  "huatasani": "Puno",
  "huaura": "Lima",
  "huay huay": "Junín",
  "huaya": "Ayacucho",
  "huayacundo arma": "Huancavelica",
  "huayan": "Áncash",
  "huayana": "Apurímac",
  "huaylas": "Áncash",
  "huaylillas": "La Libertad",
  "huayllacayan": "Áncash",
  "huayllahuara": "Huancavelica",
  "huayllan": "Áncash",
  "huayllapampa": "Áncash",
  "huayllati": "Apurímac",
  "huayllay": "Pasco",
  "huayllay grande": "Huancavelica",
  "huaynacotas": "Arequipa",
  "huayo": "La Libertad",
  "huayopata": "Cusco",
  "huayrapata": "Puno",
  "huaytara": "Huancavelica",
  "huayucachi": "Junín",
  "huepetuhe": "Madre de Dios",
  "huertas": "Junín",
  "huicungo": "San Martín",
  "huimbayoc": "San Martín",
  "humay": "Ica",
  "iberia": "Madre de Dios",
  "ichocan": "Cajamarca",
  "ichuna": "Moquegua",
  "ichupampa": "Arequipa",
  "ignacio escudero": "Piura",
  "iguain": "Ayacucho",
  "ihuari": "Lima",
  "ihuayllo": "Apurímac",
  "ilabaya": "Tacna",
  "ilave": "Puno",
  "illimo": "Lambayeque",
  "ilo": "Moquegua",
  "imaza": "Amazonas",
  "imperial": "Lima",
  "inahuaya": "Loreto",
  "inambari": "Madre de Dios",
  "inapari": "Madre de Dios",
  "incahuasi": "Lambayeque",
  "inchupalla": "Puno",
  "inclan": "Tacna",
  "indiana": "Loreto",
  "ingenio": "Junín",
  "inguilpata": "Amazonas",
  "inkawasi": "Cusco",
  "iparia": "Ucayali",
  "iquitos": "Loreto",
  "iray": "Arequipa",
  "irazola": "Ucayali",
  "islay": "Arequipa",
  "ite": "Tacna",
  "ituata": "Puno",
  "izcuchaca": "Huancavelica",
  "jacas chico": "Huánuco",
  "jacas grande": "Huánuco",
  "jacobo hunter": "Arequipa",
  "jaen": "Cajamarca",
  "jamalca": "Amazonas",
  "jangas": "Áncash",
  "janjaillo": "Junín",
  "jaqui": "Arequipa",
  "jauja": "Junín",
  "jayanca": "Lambayeque",
  "jazan": "Amazonas",
  "jeberos": "Loreto",
  "jenaro herrera": "Loreto",
  "jepelacio": "San Martín",
  "jequetepeque": "La Libertad",
  "jesus maria": "Lima",
  "jesus nazareno": "Ayacucho",
  "jilili": "Piura",
  "jircan": "Huánuco",
  "jivia": "Huánuco",
  "jorge basadre": "Tacna",
  "jorge chavez": "Cajamarca",
  "jose crespo y castillo": "Huánuco",
  "jose domingo choquehuanca": "Puno",
  "jose galvez": "Cajamarca",
  "jose leonardo ortiz": "Lambayeque",
  "jose luis bustamante y rivero": "Arequipa",
  "jose manuel quiroz": "Cajamarca",
  "jose maria arguedas": "Apurímac",
  "jose maria quimper": "Arequipa",
  "jose sabogal": "Cajamarca",
  "juan espinoza medrano": "Apurímac",
  "juan guerra": "San Martín",
  "juanjui": "San Martín",
  "julcamarca": "Huancavelica",
  "juli": "Puno",
  "juliaca": "Puno",
  "jumbilla": "Amazonas",
  "justo apu sahuaraura": "Apurímac",
  "kaquiabamba": "Apurímac",
  "kelluyo": "Puno",
  "kimbiri": "Cusco",
  "kishuara": "Apurímac",
  "kosnipata": "Cusco",
  "kunturkanki": "Cusco",
  "la arena": "Piura",
  "la banda de shilcayo": "San Martín",
  "la brea": "Piura",
  "la capilla": "Moquegua",
  "la coipa": "Cajamarca",
  "la convencion": "Cusco",
  "la cruz": "Tumbes",
  "la cuesta": "La Libertad",
  "la florida": "Cajamarca",
  "la huaca": "Piura",
  "la jalca": "Amazonas",
  "la joya": "Arequipa",
  "la libertad de pallan": "Cajamarca",
  "la mar": "Ayacucho",
  "la matanza": "Piura",
  "la molina": "Lima",
  "la morada": "Huánuco",
  "la oroya": "Junín",
  "la pampa": "Áncash",
  "la peca": "Amazonas",
  "la perla": "Callao",
  "la primavera": "Áncash",
  "la punta": "Callao",
  "la ramada": "Cajamarca",
  "la tinguina": "Ica",
  "la yarada los palos": "Tacna",
  "laberinto": "Madre de Dios",
  "lacabamba": "Áncash",
  "lachaqui": "Lima",
  "lahuaytambo": "Lima",
  "lajas": "Cajamarca",
  "lalaquiz": "Piura",
  "lamas": "San Martín",
  "lamay": "Cusco",
  "lambrama": "Apurímac",
  "lampian": "Lima",
  "lamud": "Amazonas",
  "lancones": "Piura",
  "langa": "Lima",
  "langui": "Cusco",
  "laramarca": "Huancavelica",
  "laramate": "Ayacucho",
  "laraos": "Lima",
  "laredo": "La Libertad",
  "lares": "Cusco",
  "lari": "Arequipa",
  "laria": "Huancavelica",
  "las amazonas": "Loreto",
  "las lomas": "Piura",
  "las piedras": "Madre de Dios",
  "las pirias": "Cajamarca",
  "lauricocha": "Huánuco",
  "layo": "Cusco",
  "leimebamba": "Amazonas",
  "leonor ordonez": "Junín",
  "levanto": "Amazonas",
  "limabamba": "Amazonas",
  "limatambo": "Cusco",
  "limbani": "Puno",
  "lince": "Lima",
  "lincha": "Lima",
  "lircay": "Huancavelica",
  "livitaca": "Cusco",
  "llacanora": "Cajamarca",
  "llaclin": "Áncash",
  "llalli": "Puno",
  "llamellin": "Áncash",
  "llapa": "Cajamarca",
  "llapo": "Áncash",
  "llata": "Huánuco",
  "llauta": "Ayacucho",
  "llaylla": "Junín",
  "llipa": "Áncash",
  "llipata": "Ica",
  "llochegua": "Ayacucho",
  "llocllapampa": "Junín",
  "lloque": "Moquegua",
  "llumpa": "Áncash",
  "llusco": "Cusco",
  "lluta": "Arequipa",
  "lobitos": "Piura",
  "locroja": "Huancavelica",
  "locumba": "Tacna",
  "lomas": "Arequipa",
  "longar": "Amazonas",
  "longotea": "La Libertad",
  "longuita": "Amazonas",
  "lonya chico": "Amazonas",
  "lonya grande": "Amazonas",
  "los aquijes": "Ica",
  "los banos del inca": "Cajamarca",
  "los morochucos": "Ayacucho",
  "los olivos": "Lima",
  "los organos": "Piura",
  "lucanas": "Ayacucho",
  "luis carranza": "Ayacucho",
  "lunahuana": "Lima",
  "luricocha": "Ayacucho",
  "lurigancho": "Lima",
  "lurin": "Lima",
  "luya": "Amazonas",
  "luya viejo": "Amazonas",
  "luyando": "Huánuco",
  "maca": "Arequipa",
  "macari": "Puno",
  "macate": "Áncash",
  "machaguay": "Arequipa",
  "mache": "La Libertad",
  "machupicchu": "Cusco",
  "macusani": "Puno",
  "madean": "Lima",
  "madrigal": "Arequipa",
  "magdalena de cao": "La Libertad",
  "magdalena del mar": "Lima",
  "majes": "Arequipa",
  "mala": "Lima",
  "malvas": "Áncash",
  "mamara": "Apurímac",
  "manantay": "Ucayali",
  "manas": "Lima",
  "manazo": "Puno",
  "mancora": "Piura",
  "mancos": "Áncash",
  "mangas": "Áncash",
  "manseriche": "Loreto",
  "manta": "Huancavelica",
  "manu": "Madre de Dios",
  "manuel antonio mesones muro": "Lambayeque",
  "manzanares": "Junín",
  "maquia": "Loreto",
  "mara": "Apurímac",
  "marangani": "Cusco",
  "maranon": "Huánuco",
  "maranura": "Cusco",
  "maras": "Cusco",
  "marca": "Áncash",
  "marcabal": "La Libertad",
  "marcabamba": "Ayacucho",
  "marcapata": "Cusco",
  "marcapomacocha": "Junín",
  "marcara": "Áncash",
  "marcas": "Huancavelica",
  "marcavelica": "Piura",
  "marco": "Junín",
  "marcona": "Ica",
  "margos": "Huánuco",
  "maria": "Amazonas",
  "maria parado de bellido": "Ayacucho",
  "mariano damaso beraun": "Huánuco",
  "mariano melgar": "Arequipa",
  "mariano nicolas valcarcel": "Arequipa",
  "marias": "Huánuco",
  "mariatana": "Lima",
  "mariscal benavides": "Amazonas",
  "mariscal luzuriaga": "Áncash",
  "mariscal nieto": "Moquegua",
  "mariscal ramon castilla": "Loreto",
  "marmot": "La Libertad",
  "masin": "Áncash",
  "masisea": "Ucayali",
  "masma": "Junín",
  "masma chicche": "Junín",
  "matacoto": "Áncash",
  "matahuasi": "Junín",
  "matalaque": "Moquegua",
  "matapalo": "Tumbes",
  "matara": "Cajamarca",
  "mato": "Áncash",
  "matucana": "Lima",
  "maynas": "Loreto",
  "mazamari": "Junín",
  "mazan": "Loreto",
  "megantoni": "Cusco",
  "mejia": "Arequipa",
  "melgar": "Puno",
  "mi peru": "Callao",
  "micaela bastidas": "Apurímac",
  "miguel checa": "Piura",
  "miguel iglesias": "Cajamarca",
  "milpuc": "Amazonas",
  "miracosta": "Cajamarca",
  "mirgas": "Áncash",
  "mito": "Junín",
  "moche": "La Libertad",
  "mochumi": "Lambayeque",
  "moho": "Puno",
  "molino": "Huánuco",
  "molinopampa": "Amazonas",
  "molinos": "Junín",
  "mollebamba": "La Libertad",
  "mollebaya": "Arequipa",
  "mollendo": "Arequipa",
  "mollepampa": "Huancavelica",
  "monobamba": "Junín",
  "monsefu": "Lambayeque",
  "montero": "Piura",
  "montevideo": "Amazonas",
  "monzon": "Huánuco",
  "morales": "San Martín",
  "morcolla": "Ayacucho",
  "moro": "Áncash",
  "morococha": "Junín",
  "morona": "Loreto",
  "morrope": "Lambayeque",
  "morropon": "Piura",
  "mosoc llacta": "Cusco",
  "motupe": "Lambayeque",
  "moya": "Huancavelica",
  "moyobamba": "San Martín",
  "munani": "Puno",
  "muqui": "Junín",
  "muquiyauyo": "Junín",
  "musga": "Áncash",
  "nahuimpuquio": "Huancavelica",
  "namballe": "Cajamarca",
  "namora": "Cajamarca",
  "nanchoc": "Cajamarca",
  "napo": "Loreto",
  "nauta": "Loreto",
  "navan": "Lima",
  "nazca": "Ica",
  "nepena": "Áncash",
  "neshuya": "Ucayali",
  "nicasio": "Puno",
  "nicolas de pierola": "Arequipa",
  "niepos": "Cajamarca",
  "nieva": "Amazonas",
  "ninabamba": "Cajamarca",
  "ninacaca": "Pasco",
  "nueva arica": "Lambayeque",
  "nueva cajamarca": "San Martín",
  "nueva requena": "Ucayali",
  "nueve de julio": "Junín",
  "nuevo chimbote": "Áncash",
  "nuevo imperial": "Lima",
  "nuevo occoro": "Huancavelica",
  "nuevo progreso": "San Martín",
  "nunoa": "Puno",
  "obas": "Huánuco",
  "ocalli": "Amazonas",
  "ocana": "Ayacucho",
  "ocona": "Arequipa",
  "ocongate": "Cusco",
  "ocoruro": "Cusco",
  "ocoyo": "Huancavelica",
  "ocucaje": "Ica",
  "ocumal": "Amazonas",
  "ocuviri": "Puno",
  "ollachea": "Puno",
  "ollantaytambo": "Cusco",
  "ollaraya": "Puno",
  "olmos": "Lambayeque",
  "omacha": "Cusco",
  "omas": "Lima",
  "omate": "Moquegua",
  "omia": "Amazonas",
  "ondores": "Junín",
  "ongon": "La Libertad",
  "ongoy": "Apurímac",
  "orcopampa": "Arequipa",
  "orcotuna": "Junín",
  "oronccoy": "Ayacucho",
  "orurillo": "Puno",
  "otoca": "Ayacucho",
  "otuzco": "La Libertad",
  "oxamarca": "Cajamarca",
  "oxapampa": "Pasco",
  "oyolo": "Ayacucho",
  "oyon": "Lima",
  "oyotun": "Lambayeque",
  "paca": "Junín",
  "pacaipampa": "Piura",
  "pacanga": "La Libertad",
  "pacapausa": "Ayacucho",
  "pacaran": "Lima",
  "pacaraos": "Lima",
  "pacasmayo": "La Libertad",
  "pacaycasa": "Ayacucho",
  "paccaritambo": "Cusco",
  "paccho": "Lima",
  "pachacamac": "Lima",
  "pachaconas": "Apurímac",
  "pachacutec": "Ica",
  "pachamarca": "Huancavelica",
  "pachangara": "Lima",
  "pachas": "Huánuco",
  "pachia": "Tacna",
  "pachitea": "Huánuco",
  "pachiza": "San Martín",
  "pacllon": "Áncash",
  "pacobamba": "Apurímac",
  "pacocha": "Moquegua",
  "pacora": "Lambayeque",
  "pacucha": "Apurímac",
  "padre abad": "Ucayali",
  "padre marquez": "Loreto",
  "paico": "Ayacucho",
  "paijan": "La Libertad",
  "paimas": "Piura",
  "paita": "Piura",
  "pajarillo": "San Martín",
  "palcamayo": "Junín",
  "palcazu": "Pasco",
  "pallanchacra": "Pasco",
  "pallasca": "Áncash",
  "pallpata": "Cusco",
  "palpa": "Ica",
  "pampachiri": "Apurímac",
  "pampacolca": "Arequipa",
  "pamparomas": "Áncash",
  "pampas chico": "Áncash",
  "pampas de hospital": "Tumbes",
  "pampas grande": "Áncash",
  "panao": "Huánuco",
  "pancan": "Junín",
  "pangoa": "Junín",
  "papaplaya": "San Martín",
  "papayal": "Tumbes",
  "paracas": "Ica",
  "paramonga": "Lima",
  "paranday": "La Libertad",
  "pararca": "Ayacucho",
  "pararin": "Áncash",
  "paras": "Ayacucho",
  "paratia": "Puno",
  "parco": "Junín",
  "parcona": "Ica",
  "parcoy": "La Libertad",
  "pardo miguel": "San Martín",
  "pariacoto": "Áncash",
  "parinacochas": "Ayacucho",
  "parinari": "Loreto",
  "parinas": "Piura",
  "parobamba": "Áncash",
  "paruro": "Cusco",
  "pastaza": "Loreto",
  "patambuco": "Puno",
  "patapo": "Lambayeque",
  "pataypampa": "Apurímac",
  "pataz": "La Libertad",
  "pativilca": "Lima",
  "paucar": "Pasco",
  "paucar del sara sara": "Ayacucho",
  "paucara": "Huancavelica",
  "paucarbamba": "Huancavelica",
  "paucarcolla": "Puno",
  "paucarpata": "Arequipa",
  "paucas": "Áncash",
  "pausa": "Ayacucho",
  "pazos": "Huancavelica",
  "pebas": "Loreto",
  "pedro galvez": "Cajamarca",
  "pedro vilca apaza": "Puno",
  "perene": "Junín",
  "phara": "Puno",
  "pias": "La Libertad",
  "pichacani": "Puno",
  "pichanaqui": "Junín",
  "pichari": "Cusco",
  "pichigua": "Cusco",
  "pichirhua": "Apurímac",
  "pichos": "Huancavelica",
  "picota": "San Martín",
  "picsi": "Lambayeque",
  "pilchaca": "Huancavelica",
  "pilcomayo": "Junín",
  "pilcuyo": "Puno",
  "pillco marca": "Huánuco",
  "pillpinto": "Cusco",
  "pilluana": "San Martín",
  "pilpichaca": "Huancavelica",
  "pimentel": "Lambayeque",
  "pimpingos": "Cajamarca",
  "pinra": "Huánuco",
  "pinto recodo": "San Martín",
  "pion": "Cajamarca",
  "pira": "Áncash",
  "pisac": "Cusco",
  "pisacoma": "Puno",
  "pisco": "Ica",
  "piscobamba": "Áncash",
  "piscoyacu": "San Martín",
  "pisuquia": "Amazonas",
  "pitipo": "Lambayeque",
  "pitumarca": "Cusco",
  "plateria": "Puno",
  "pocohuanca": "Apurímac",
  "pocollay": "Tacna",
  "pocsi": "Arequipa",
  "polobaya": "Arequipa",
  "polvora": "San Martín",
  "pomabamba": "Áncash",
  "pomacancha": "Junín",
  "pomacanchi": "Cusco",
  "pomahuaca": "Cajamarca",
  "pomalca": "Lambayeque",
  "pomata": "Puno",
  "ponto": "Áncash",
  "poroto": "La Libertad",
  "poroy": "Cusco",
  "posic": "San Martín",
  "potoni": "Puno",
  "pozuzo": "Pasco",
  "progreso": "Apurímac",
  "providencia": "Amazonas",
  "pucacaca": "San Martín",
  "pucacolpa": "Ayacucho",
  "pucala": "Lambayeque",
  "pucayacu": "Huánuco",
  "pucusana": "Lima",
  "pucyura": "Cusco",
  "puente piedra": "Lima",
  "puerto bermudez": "Pasco",
  "puerto inca": "Huánuco",
  "puinahua": "Loreto",
  "pulan": "Cajamarca",
  "pullo": "Ayacucho",
  "punchana": "Loreto",
  "punchao": "Huánuco",
  "punos": "Huánuco",
  "punta de bombon": "Arequipa",
  "punta hermosa": "Lima",
  "punta negra": "Lima",
  "puquina": "Moquegua",
  "puquio": "Ayacucho",
  "purus": "Ucayali",
  "pusi": "Puno",
  "putina": "Puno",
  "putinza": "Lima",
  "putumayo": "Loreto",
  "puyca": "Arequipa",
  "puyusca": "Ayacucho",
  "quechualla": "Arequipa",
  "quehue": "Cusco",
  "quellouno": "Cusco",
  "quequena": "Arequipa",
  "querco": "Huancavelica",
  "querecotillo": "Piura",
  "querobamba": "Ayacucho",
  "querocotillo": "Cajamarca",
  "querocoto": "Cajamarca",
  "queropalca": "Huánuco",
  "quiaca": "Puno",
  "quicacha": "Arequipa",
  "quiches": "Áncash",
  "quichuas": "Huancavelica",
  "quichuay": "Junín",
  "quilahuani": "Tacna",
  "quilca": "Arequipa",
  "quilcapuncu": "Puno",
  "quilcas": "Junín",
  "quillo": "Áncash",
  "quilmana": "Lima",
  "quinches": "Lima",
  "quinistaquillas": "Moquegua",
  "quinjalca": "Amazonas",
  "quinocay": "Lima",
  "quinota": "Cusco",
  "quinua": "Ayacucho",
  "quinuabamba": "Áncash",
  "quiquijana": "Cusco",
  "quiruvilca": "La Libertad",
  "quishuar": "Huancavelica",
  "quispicanchi": "Cusco",
  "quisqui": "Huánuco",
  "quito arma": "Huancavelica",
  "quivilla": "Huánuco",
  "ragash": "Áncash",
  "rahuapampa": "Áncash",
  "ramon castilla": "Loreto",
  "ranracancha": "Apurímac",
  "ranrahirca": "Áncash",
  "rapayan": "Áncash",
  "raymondi": "Ucayali",
  "razuri": "La Libertad",
  "recta": "Amazonas",
  "recuay": "Áncash",
  "reque": "Lambayeque",
  "requena": "Loreto",
  "ricardo palma": "Lima",
  "ricran": "Junín",
  "rimac": "Lima",
  "rinconada llicuar": "Piura",
  "rio negro": "Junín",
  "rio santiago": "Amazonas",
  "rio tambo": "Junín",
  "rioja": "San Martín",
  "ripan": "Huánuco",
  "roble": "Huancavelica",
  "rodriguez de mendoza": "Amazonas",
  "rondocan": "Cusco",
  "rondos": "Huánuco",
  "rosa panduro": "Loreto",
  "rosario": "Huancavelica",
  "rosaspata": "Puno",
  "rumisapa": "San Martín",
  "rupa rupa": "Huánuco",
  "sabaino": "Apurímac",
  "sabandia": "Arequipa",
  "sacanche": "San Martín",
  "sachaca": "Arequipa",
  "sacsamarca": "Ayacucho",
  "saisa": "Ayacucho",
  "salamanca": "Arequipa",
  "salaverry": "La Libertad",
  "salcabamba": "Huancavelica",
  "salcahuasi": "Huancavelica",
  "salitral": "Piura",
  "sallique": "Cajamarca",
  "salpo": "La Libertad",
  "sama": "Tacna",
  "saman": "Puno",
  "samanco": "Áncash",
  "samegua": "Moquegua",
  "samuel pastor": "Arequipa",
  "samugari": "Ayacucho",
  "san agustin": "Junín",
  "san andres": "Ica",
  "san andres de cutervo": "Cajamarca",
  "san andres de tupicocha": "Lima",
  "san anton": "Puno",
  "san antonio de antaparco": "Huancavelica",
  "san antonio de cachi": "Apurímac",
  "san antonio de chuca": "Arequipa",
  "san antonio de cusicancha": "Huancavelica",
  "san antonio de putina": "Puno",
  "san bartolo": "Lima",
  "san bartolome": "Lima",
  "san benito": "Cajamarca",
  "san bernardino": "Cajamarca",
  "san borja": "Lima",
  "san carlos": "Amazonas",
  "san clemente": "Ica",
  "san cristobal de rajan": "Áncash",
  "san damian": "Lima",
  "san felipe": "Cajamarca",
  "san fernando": "San Martín",
  "san francisco": "Huánuco",
  "san francisco de asis": "Huánuco",
  "san francisco de asis de yarusyacan": "Pasco",
  "san francisco de cayran": "Huánuco",
  "san francisco de daguas": "Amazonas",
  "san francisco de ravacayco": "Ayacucho",
  "san francisco de sangayaico": "Huancavelica",
  "san francisco del yeso": "Amazonas",
  "san gaban": "Puno",
  "san gregorio": "Cajamarca",
  "san hilarion": "San Martín",
  "san ignacio": "Cajamarca",
  "san isidro de maino": "Amazonas",
  "san jacinto": "Tumbes",
  "san javier de alpabamba": "Ayacucho",
  "san jeronimo de tunan": "Junín",
  "san joaquin": "Lima",
  "san jose de los molinos": "Ica",
  "san jose de lourdes": "Cajamarca",
  "san jose de quero": "Junín",
  "san jose de sisa": "San Martín",
  "san jose de ticllas": "Ayacucho",
  "san jose de ushua": "Ayacucho",
  "san jose del alto": "Cajamarca",
  "san juan de bigote": "Piura",
  "san juan de chacna": "Apurímac",
  "san juan de cutervo": "Cajamarca",
  "san juan de iris": "Lima",
  "san juan de iscos": "Junín",
  "san juan de jarpa": "Junín",
  "san juan de la virgen": "Tumbes",
  "san juan de licupis": "Cajamarca",
  "san juan de lopecancha": "Amazonas",
  "san juan de lurigancho": "Lima",
  "san juan de miraflores": "Lima",
  "san juan de rontoy": "Áncash",
  "san juan de salinas": "Puno",
  "san juan de siguas": "Arequipa",
  "san juan de tantaranche": "Lima",
  "san juan de tarucani": "Arequipa",
  "san juan de yanac": "Ica",
  "san juan del oro": "Puno",
  "san lorenzo": "Junín",
  "san lorenzo de quinti": "Lima",
  "san luis de lucma": "Cajamarca",
  "san luis de shuaro": "Junín",
  "san marcos de rocchac": "Huancavelica",
  "san martin de porres": "Lima",
  "san mateo": "Lima",
  "san mateo de otao": "Lima",
  "san miguel de aco": "Áncash",
  "san miguel de acos": "Lima",
  "san miguel de cauri": "Huánuco",
  "san miguel de chaccrampa": "Apurímac",
  "san miguel de corpanqui": "Áncash",
  "san miguel de el faique": "Piura",
  "san miguel de mayocc": "Huancavelica",
  "san pablo de pillao": "Huánuco",
  "san pedro de cachora": "Apurímac",
  "san pedro de cajas": "Junín",
  "san pedro de casta": "Lima",
  "san pedro de chana": "Áncash",
  "san pedro de chaulan": "Huánuco",
  "san pedro de chunan": "Junín",
  "san pedro de coris": "Huancavelica",
  "san pedro de huacarpana": "Ica",
  "san pedro de huancayre": "Lima",
  "san pedro de larcay": "Ayacucho",
  "san pedro de lloc": "La Libertad",
  "san pedro de palco": "Ayacucho",
  "san pedro de pilas": "Lima",
  "san pedro de pillao": "Pasco",
  "san pedro de putina punco": "Puno",
  "san ramon": "Junín",
  "san roman": "Puno",
  "san roque de cumbaza": "San Martín",
  "san salvador": "Cusco",
  "san salvador de quije": "Ayacucho",
  "san sebastian": "Cusco",
  "san silvestre de cochan": "Cajamarca",
  "san vicente de canete": "Lima",
  "sana": "Lambayeque",
  "sanagoran": "La Libertad",
  "sanayca": "Apurímac",
  "sanchez carrion": "La Libertad",
  "sancos": "Ayacucho",
  "sandia": "Puno",
  "sangallaya": "Lima",
  "sangarara": "Cusco",
  "sano": "Junín",
  "santa": "Áncash",
  "santa ana de huaycahuacho": "Ayacucho",
  "santa ana de tusi": "Pasco",
  "santa anita": "Lima",
  "santa barbara de carhuacayan": "Junín",
  "santa catalina": "Amazonas",
  "santa catalina de mossa": "Piura",
  "santa cruz de andamarca": "Lima",
  "santa cruz de chuca": "La Libertad",
  "santa cruz de cocachacra": "Lima",
  "santa cruz de flores": "Lima",
  "santa cruz de toledo": "Cajamarca",
  "santa eulalia": "Lima",
  "santa isabel de siguas": "Arequipa",
  "santa leonor": "Lima",
  "santa maria": "Lima",
  "santa maria de chicmo": "Apurímac",
  "santa maria del mar": "Lima",
  "santa maria del valle": "Huánuco",
  "santa rita de siguas": "Arequipa",
  "santa rosa de alto yanajanca": "Huánuco",
  "santa rosa de ocopa": "Junín",
  "santa rosa de quives": "Lima",
  "santa rosa de sacco": "Junín",
  "santa teresa": "Cusco",
  "santiago de anchucaya": "Lima",
  "santiago de cao": "La Libertad",
  "santiago de challas": "La Libertad",
  "santiago de chilcas": "Áncash",
  "santiago de chocorvos": "Huancavelica",
  "santiago de chuco": "La Libertad",
  "santiago de lucanamarca": "Ayacucho",
  "santiago de paucaray": "Ayacucho",
  "santiago de pischa": "Ayacucho",
  "santiago de pupuja": "Puno",
  "santiago de quirahuara": "Huancavelica",
  "santiago de surco": "Lima",
  "santiago de tucuma": "Huancavelica",
  "santiago de tuna": "Lima",
  "santillana": "Ayacucho",
  "santo domingo": "Piura",
  "santo domingo de acobamba": "Junín",
  "santo domingo de anda": "Huánuco",
  "santo domingo de capillas": "Huancavelica",
  "santo domingo de la capilla": "Cajamarca",
  "santo domingo de los olleros": "Lima",
  "santo tomas de pata": "Huancavelica",
  "santo toribio": "Áncash",
  "sapallanga": "Junín",
  "sapillica": "Piura",
  "saposoa": "San Martín",
  "saquena": "Loreto",
  "sara sara": "Ayacucho",
  "sarayacu": "Loreto",
  "sarhua": "Ayacucho",
  "sarin": "La Libertad",
  "sartimbamba": "La Libertad",
  "satipo": "Junín",
  "sauce": "San Martín",
  "saucepampa": "Cajamarca",
  "saurama": "Ayacucho",
  "sausa": "Junín",
  "sayan": "Lima",
  "sayapullo": "La Libertad",
  "sayla": "Arequipa",
  "saylla": "Cusco",
  "secclla": "Huancavelica",
  "sechura": "Piura",
  "sepahua": "Ucayali",
  "sexi": "Cajamarca",
  "shamboyacu": "San Martín",
  "shanao": "San Martín",
  "shapaja": "San Martín",
  "shatoja": "San Martín",
  "shilla": "Áncash",
  "shipasbamba": "Amazonas",
  "shunqui": "Huánuco",
  "shunte": "San Martín",
  "shupluy": "Áncash",
  "sibayo": "Arequipa",
  "sicaya": "Junín",
  "sicchez": "Piura",
  "sicsibamba": "Áncash",
  "sicuani": "Cusco",
  "sihuas": "Áncash",
  "sillapata": "Huánuco",
  "simbal": "La Libertad",
  "simon bolivar": "Pasco",
  "sina": "Puno",
  "sincos": "Junín",
  "singa": "Huánuco",
  "sinsicap": "La Libertad",
  "sitabamba": "La Libertad",
  "sitacocha": "Cajamarca",
  "sitajara": "Tacna",
  "sivia": "Ayacucho",
  "socabaya": "Arequipa",
  "socos": "Ayacucho",
  "socota": "Cajamarca",
  "soloco": "Amazonas",
  "sonche": "Amazonas",
  "sondor": "Piura",
  "sondorillo": "Piura",
  "soplin": "Loreto",
  "soras": "Ayacucho",
  "soraya": "Apurímac",
  "soritor": "San Martín",
  "sorochuco": "Cajamarca",
  "subtanjalla": "Ica",
  "succha": "Áncash",
  "suitucancha": "Junín",
  "sullana": "Piura",
  "sumbilca": "Lima",
  "sunampe": "Ica",
  "supe": "Lima",
  "supe puerto": "Lima",
  "surco": "Lima",
  "surcubamba": "Huancavelica",
  "surquillo": "Lima",
  "susapaya": "Tacna",
  "suyckutambo": "Cusco",
  "suyo": "Piura",
  "tabaconas": "Cajamarca",
  "tabalosos": "San Martín",
  "tacabamba": "Cajamarca",
  "tahuamanu": "Madre de Dios",
  "tahuania": "Ucayali",
  "talara": "Piura",
  "talavera": "Apurímac",
  "tamarindo": "Piura",
  "tambillo": "Ayacucho",
  "tambo de mora": "Ica",
  "tambo grande": "Piura",
  "tambobamba": "Apurímac",
  "tambopata": "Madre de Dios",
  "tamburco": "Apurímac",
  "tanta": "Lima",
  "tantamayo": "Huánuco",
  "tantara": "Huancavelica",
  "tantarica": "Cajamarca",
  "tapacocha": "Áncash",
  "tapairihua": "Apurímac",
  "tapay": "Arequipa",
  "tapiche": "Loreto",
  "tapo": "Junín",
  "tapuc": "Pasco",
  "taraco": "Puno",
  "tarapoto": "San Martín",
  "tarata": "Tacna",
  "taray": "Cusco",
  "tarica": "Áncash",
  "tarma": "Junín",
  "tarucachi": "Tacna",
  "tate": "Ica",
  "tauca": "Áncash",
  "tauria": "Arequipa",
  "taurija": "La Libertad",
  "tauripampa": "Lima",
  "tayabamba": "La Libertad",
  "tayacaja": "Huancavelica",
  "teniente cesar lopez rojas": "Loreto",
  "teniente manuel clavero": "Loreto",
  "tiabaya": "Arequipa",
  "tibillo": "Ica",
  "ticaco": "Tacna",
  "ticapampa": "Áncash",
  "ticlacayan": "Pasco",
  "ticllos": "Áncash",
  "ticrapo": "Huancavelica",
  "tigre": "Loreto",
  "tilali": "Puno",
  "tinco": "Áncash",
  "tingo": "Amazonas",
  "tingo de ponasa": "San Martín",
  "tingo de saposoa": "San Martín",
  "tinicachi": "Puno",
  "tinta": "Cusco",
  "tintay": "Apurímac",
  "tintay puncu": "Huancavelica",
  "tinyahuarco": "Pasco",
  "tipan": "Arequipa",
  "tiquillaca": "Puno",
  "tirapata": "Puno",
  "tisco": "Arequipa",
  "tocache": "San Martín",
  "tocmoche": "Cajamarca",
  "tomas": "Lima",
  "tomay kichwa": "Huánuco",
  "tomepampa": "Arequipa",
  "tongod": "Cajamarca",
  "torata": "Moquegua",
  "toraya": "Apurímac",
  "toribio casanova": "Cajamarca",
  "toro": "Arequipa",
  "torres causana": "Loreto",
  "totora": "Amazonas",
  "totos": "Ayacucho",
  "tournavista": "Huánuco",
  "tres de diciembre": "Junín",
  "tres unidos": "San Martín",
  "trita": "Amazonas",
  "trompeteros": "Loreto",
  "trujillo": "La Libertad",
  "tucume": "Lambayeque",
  "tuman": "Lambayeque",
  "tumay huaraca": "Apurímac",
  "tumbaden": "Cajamarca",
  "tunan marca": "Junín",
  "tupac amaru": "Cusco",
  "tupac amaru inca": "Ica",
  "tupe": "Lima",
  "turpay": "Apurímac",
  "turpo": "Apurímac",
  "tuti": "Arequipa",
  "ubinas": "Moquegua",
  "uchiza": "San Martín",
  "uchumarca": "La Libertad",
  "uchumayo": "Arequipa",
  "uchuraccay": "Ayacucho",
  "uco": "Áncash",
  "ucuncha": "La Libertad",
  "ulcumayo": "Junín",
  "umachiri": "Puno",
  "umari": "Huánuco",
  "unicachi": "Puno",
  "union agua blanca": "Cajamarca",
  "unon": "Arequipa",
  "upahuacho": "Ayacucho",
  "uraca": "Arequipa",
  "uranmarca": "Apurímac",
  "urarinas": "Loreto",
  "urcos": "Cusco",
  "urpay": "La Libertad",
  "urubamba": "Cusco",
  "usicayos": "Puno",
  "usquil": "La Libertad",
  "utco": "Cajamarca",
  "utcubamba": "Amazonas",
  "uticyacu": "Cajamarca",
  "valera": "Amazonas",
  "vargas guerra": "Loreto",
  "vegueta": "Lima",
  "veintiseis de octubre": "Piura",
  "veintisiete de noviembre": "Lima",
  "velille": "Cusco",
  "ventanilla": "Callao",
  "vicco": "Pasco",
  "vice": "Piura",
  "vichayal": "Piura",
  "victor fajardo": "Ayacucho",
  "victor larco herrera": "La Libertad",
  "vilavila": "Puno",
  "vilca": "Huancavelica",
  "vilcanchos": "Ayacucho",
  "vilcas huaman": "Ayacucho",
  "villa el salvador": "Lima",
  "villa kintiarina": "Cusco",
  "villa maria del triunfo": "Lima",
  "villa rica": "Pasco",
  "villa virgen": "Cusco",
  "vilque": "Puno",
  "vilque chico": "Puno",
  "vinac": "Lima",
  "vinchos": "Ayacucho",
  "viques": "Junín",
  "viraco": "Arequipa",
  "viru": "La Libertad",
  "virundo": "Apurímac",
  "vischongo": "Ayacucho",
  "vitis": "Lima",
  "vitoc": "Junín",
  "vitor": "Arequipa",
  "vizcatan del ene": "Junín",
  "wanchaq": "Cusco",
  "yacus": "Huánuco",
  "yaguas": "Loreto",
  "yamango": "Piura",
  "yambrasbamba": "Amazonas",
  "yamon": "Amazonas",
  "yanac": "Áncash",
  "yanaca": "Apurímac",
  "yanahuanca": "Pasco",
  "yanahuara": "Arequipa",
  "yanahuaya": "Puno",
  "yanama": "Áncash",
  "yanaoca": "Cusco",
  "yanaquihua": "Arequipa",
  "yanas": "Huánuco",
  "yanatile": "Cusco",
  "yanque": "Arequipa",
  "yantalo": "San Martín",
  "yaquerana": "Loreto",
  "yarabamba": "Arequipa",
  "yarinacocha": "Ucayali",
  "yarowilca": "Huánuco",
  "yarumayo": "Huánuco",
  "yauca": "Arequipa",
  "yauca del rosario": "Ica",
  "yaurisque": "Cusco",
  "yautan": "Áncash",
  "yauya": "Áncash",
  "yauyucan": "Cajamarca",
  "yavari": "Loreto",
  "yonan": "Cajamarca",
  "yorongos": "San Martín",
  "yucay": "Cusco",
  "yunga": "Moquegua",
  "yungar": "Áncash",
  "yungay": "Áncash",
  "yunguyo": "Puno",
  "yupan": "Áncash",
  "yura": "Arequipa",
  "yuracmarca": "Áncash",
  "yuracyacu": "San Martín",
  "yurimaguas": "Loreto",
  "yurua": "Ucayali",
  "yuyapichis": "Huánuco",
  "zapatero": "San Martín",
  "zarumilla": "Tumbes",
  "zepita": "Puno",
  "zorritos": "Tumbes",
  "zuniga": "Lima",
  "zurite": "Cusco",
}
